-- MariaDB dump 10.19  Distrib 10.4.32-MariaDB, for Win64 (AMD64)
--
-- Host: localhost    Database: epes_db
-- ------------------------------------------------------
-- Server version	10.4.32-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `help_docs`
--

LOCK TABLES `help_docs` WRITE;
/*!40000 ALTER TABLE `help_docs` DISABLE KEYS */;
INSERT INTO `help_docs` VALUES (1,'Getting Started','System Overview','\n                <h3>Welcome to EPES</h3>\n                <p>The Employee Performance Evaluation System (EPES) is designed to streamline faculty performance documentation and evaluation at DEBESMSCAT.</p>\n                <h4>Key Features:</h4>\n                <ul>\n                    <li>Digital IPCR submission and tracking</li>\n                    <li>Automated performance calculations</li>\n                    <li>Real-time progress monitoring</li>\n                    <li>Comprehensive analytics and reporting</li>\n                    <li>Evidence-based decision making support</li>\n                </ul>\n            ',1,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (2,'Getting Started','User Roles and Permissions','\n                <h3>User Roles</h3>\n                <p>EPES has three main user roles:</p>\n                <h4>1. Faculty Member</h4>\n                <ul>\n                    <li>Submit tasks and accomplishments</li>\n                    <li>View performance ratings</li>\n                    <li>Generate IPCR reports</li>\n                    <li>Track progress in real-time</li>\n                </ul>\n                <h4>2. Evaluator/Department Head</h4>\n                <ul>\n                    <li>Review and verify faculty submissions</li>\n                    <li>Provide ratings and feedback</li>\n                    <li>Generate department reports</li>\n                    <li>Monitor faculty performance</li>\n                </ul>\n                <h4>3. Administrator</h4>\n                <ul>\n                    <li>Manage users and roles</li>\n                    <li>Configure system settings</li>\n                    <li>Generate institutional reports</li>\n                    <li>Oversee evaluation periods</li>\n                </ul>\n            ',2,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (3,'Faculty Guide','How to Submit Tasks','\n                <h3>Submitting Your Tasks</h3>\n                <ol>\n                    <li>Navigate to <strong>Targets</strong> menu</li>\n                    <li>Select the task you want to submit</li>\n                    <li>Click <strong>Submit File</strong></li>\n                    <li>Upload your supporting documents (PDF, DOC, DOCX, images)</li>\n                    <li>Add progress notes if needed</li>\n                    <li>Click <strong>Submit</strong></li>\n                </ol>\n                <h4>File Requirements:</h4>\n                <ul>\n                    <li>Maximum file size: 10MB</li>\n                    <li>Allowed formats: PDF, DOC, DOCX, JPG, PNG, XLS, XLSX</li>\n                    <li>Ensure files are clearly labeled</li>\n                </ul>\n            ',3,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (4,'Faculty Guide','Viewing Your Performance','\n                <h3>Performance Dashboard</h3>\n                <p>Your dashboard shows:</p>\n                <ul>\n                    <li><strong>Total Targets:</strong> Number of tasks assigned to your position</li>\n                    <li><strong>Submitted:</strong> Tasks you have submitted</li>\n                    <li><strong>For Verification:</strong> Tasks awaiting evaluator review</li>\n                    <li><strong>Verified:</strong> Tasks approved by your evaluator</li>\n                </ul>\n                <h3>Performance Metrics:</h3>\n                <ul>\n                    <li><strong>Efficiency:</strong> How well you utilize resources</li>\n                    <li><strong>Timeliness:</strong> Meeting deadlines</li>\n                    <li><strong>Quality:</strong> Quality of work submitted</li>\n                </ul>\n            ',4,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (5,'Evaluator Guide','How to Verify Tasks','\n                <h3>Verifying Faculty Submissions</h3>\n                <ol>\n                    <li>Go to <strong>Faculty Evaluation</strong> menu</li>\n                    <li>Select the faculty member</li>\n                    <li>Review submitted tasks and evidence</li>\n                    <li>Provide ratings for:</li>\n                    <ul>\n                        <li>Efficiency (1-5 scale)</li>\n                        <li>Timeliness (1-5 scale)</li>\n                        <li>Quality (1-5 scale)</li>\n                    </ul>\n                    <li>Add comments or feedback</li>\n                    <li>Click <strong>Verify</strong> to approve</li>\n                </ol>\n                <h4>Rating Guidelines:</h4>\n                <ul>\n                    <li>5 - Outstanding</li>\n                    <li>4 - Very Satisfactory</li>\n                    <li>3 - Satisfactory</li>\n                    <li>2 - Unsatisfactory</li>\n                    <li>1 - Poor</li>\n                </ul>\n            ',5,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (6,'Evaluator Guide','Generating Recommendations','\n                <h3>Contract Renewal Recommendations</h3>\n                <p>For COS faculty, evaluators must provide renewal recommendations:</p>\n                <ol>\n                    <li>Navigate to <strong>Recommendation</strong> menu</li>\n                    <li>Review faculty performance data</li>\n                    <li>System calculates overall score automatically</li>\n                    <li>Provide recommendation:</li>\n                    <ul>\n                        <li><strong>Recommended</strong> - For renewal</li>\n                        <li><strong>Not Recommended</strong> - Not for renewal</li>\n                    </ul>\n                    <li>Add statement of reason</li>\n                    <li>Submit for Dean review</li>\n                </ol>\n            ',6,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (7,'Admin Guide','Managing Users','\n                <h3>User Management</h3>\n                <h4>Adding New Faculty:</h4>\n                <ol>\n                    <li>Go to <strong>Employees > Add New</strong></li>\n                    <li>Fill in required information</li>\n                    <li>Assign department and position</li>\n                    <li>Assign evaluator</li>\n                    <li>Save and notify user</li>\n                </ol>\n                <h4>Resetting Password:</h4>\n                <ol>\n                    <li>Go to user list</li>\n                    <li>Click <strong>Reset Password</strong></li>\n                    <li>System sends reset link via email</li>\n                </ol>\n            ',7,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (8,'Admin Guide','Configuring Rating Period','\n                <h3>Setting Rating Period</h3>\n                <ol>\n                    <li>Navigate to <strong>Rating Period</strong></li>\n                    <li>Select semester:</li>\n                    <ul>\n                        <li>1st Semester</li>\n                        <li>2nd Semester</li>\n                        <li>Summer</li>\n                    </ul>\n                    <li>Enter academic year (e.g., 2024-2025)</li>\n                    <li>Set as active period</li>\n                </ol>\n                <p><strong>Note:</strong> Only one rating period can be active at a time.</p>\n            ',8,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (9,'Reports','Generating IPCR Report','\n                <h3>Individual Performance Commitment and Review</h3>\n                <ol>\n                    <li>Go to your <strong>Dashboard</strong></li>\n                    <li>Click <strong>Generate IPCR</strong></li>\n                    <li>Select rating period</li>\n                    <li>Review the generated form</li>\n                    <li>Download as PDF</li>\n                </ol>\n                <p>The IPCR form includes:</p>\n                <ul>\n                    <li>Performance ratings by criterion</li>\n                    <li>Task accomplishments</li>\n                    <li>Overall score and adjectival rating</li>\n                    <li>Signature sections</li>\n                </ul>\n            ',9,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (10,'Reports','Generating OPCR Summary','\n                <h3>Office Performance Commitment and Review</h3>\n                <p>For Administrators and Deans:</p>\n                <ol>\n                    <li>Go to <strong>Reports > OPCR Summary</strong></li>\n                    <li>Select department</li>\n                    <li>Select rating period</li>\n                    <li>Generate report</li>\n                </ol>\n                <p>The OPCR summary includes:</p>\n                <ul>\n                    <li>Department performance metrics</li>\n                    <li>Faculty count and participation</li>\n                    <li>Overall averages</li>\n                    <li>Comparative analysis</li>\n                </ul>\n            ',10,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
INSERT INTO `help_docs` VALUES (11,'Troubleshooting','Common Issues','\n                <h3>Frequently Encountered Problems</h3>\n                <h4>Cannot Login</h4>\n                <ul>\n                    <li>Verify email and password</li>\n                    <li>Check if account is activated</li>\n                    <li>Use \"Forgot Password\" if needed</li>\n                    <li>Contact admin if account is locked</li>\n                </ul>\n                <h4>File Upload Failed</h4>\n                <ul>\n                    <li>Check file size (max 10MB)</li>\n                    <li>Verify file format is allowed</li>\n                    <li>Ensure stable internet connection</li>\n                </ul>\n                <h4>Cannot Submit Task</h4>\n                <ul>\n                    <li>Ensure task is assigned to you</li>\n                    <li>Check if rating period is active</li>\n                    <li>Verify all required fields are filled</li>\n                </ul>\n            ',11,1,'2026-06-18 15:26:03','2026-06-18 15:26:03');
/*!40000 ALTER TABLE `help_docs` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `rating_period`
--

LOCK TABLES `rating_period` WRITE;
/*!40000 ALTER TABLE `rating_period` DISABLE KEYS */;
INSERT INTO `rating_period` VALUES (2,'1st Semester','2023-2024','2023-08-15','2023-12-20',1,'IPCR-1stSemester-2023-2024','IPCR',1);
INSERT INTO `rating_period` VALUES (3,'1st Semester','2023-2024','2023-12-21','2024-01-15',1,'DP-1stSemester-2023-2024','DP',1);
INSERT INTO `rating_period` VALUES (4,'1st Semester','2023-2024','2024-01-16','2024-01-31',0,'OPCR-1stSemester-2023-2024','OPCR',1);
INSERT INTO `rating_period` VALUES (5,'2nd Semester','2023-2024','2024-01-20','2024-05-25',1,'IPCR-2ndSemester-2023-2024','IPCR',1);
INSERT INTO `rating_period` VALUES (6,'2nd Semester','2023-2024','2024-05-26','2024-06-15',1,'DP-2ndSemester-2023-2024','DP',1);
INSERT INTO `rating_period` VALUES (7,'2nd Semester','2023-2024','2024-06-16','2024-06-30',0,'OPCR-2ndSemester-2023-2024','OPCR',1);
INSERT INTO `rating_period` VALUES (8,'1st Semester','2024-2025','2024-08-15','2024-12-20',1,'IPCR-1stSemester-2024-2025','IPCR',1);
INSERT INTO `rating_period` VALUES (9,'1st Semester','2024-2025','2024-12-21','2025-01-15',1,'DP-1stSemester-2024-2025','DP',1);
INSERT INTO `rating_period` VALUES (10,'1st Semester','2024-2025','2025-01-16','2025-01-31',0,'OPCR-1stSemester-2024-2025','OPCR',1);
/*!40000 ALTER TABLE `rating_period` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-06-19  8:36:10
